org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.186
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=alyrioncore
mod_name=AlyrionCore
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=xyz.alyrion.alyrioncore
mod_authors=Alyrion Team
mod_description=Custom core mod for the Alyrion SMP featuring a scientifically accurate Mars dimension and planetary systems.
